### PR TITLE
Make examples build on cloud web editor

### LINKED ISSUE #411: Library does not compile from the Arduino Cloud IDE for MKR Wi-Fi 1010
```
/usr/local/bin/arduino-cli compile --fqbn arduino:samd:mkrwifi1010 --build-cache-path /tmp --output-dir /tmp/3214616684/build --build-path /tmp/arduino-build-5FBB2B82E8C1BA32B234A5C999B03F04  /tmp/3214616684/ArduinoIoTCloud_Basic

In file included from /tmp/3214616684/ArduinoIoTCloud_Basic/ArduinoIoTCloud_Basic.ino:18:0:
/tmp/3214616684/ArduinoIoTCloud_Basic/thingProperties.h:3:4: error: #error "Please check Arduino IoT Cloud supported boards list: https://github.com/arduino-libraries/ArduinoIoTCloud/#what"
   #error "Please check Arduino IoT Cloud supported boards list: https://github.com/arduino-libraries/ArduinoIoTCloud/#what"
    ^~~~~

Error during build: exit status 1
```

### PR DESCRIPTION
**Pull request by pennam**
Fixes #411

### CODE REVIEW

File: examples/ArduinoIoTCloud-Advanced/arduino_secrets.h [hunk 1]
```diff
@@ -1,6 +1,3 @@
-#include <ArduinoIoTCloud.h>
-#include <Arduino_ConnectionHandler.h>
```
Comment (per1234) [inline examples/ArduinoIoTCloud-Advanced/arduino_secrets.h:2]: Although it is not technically required, I think the code is more intuitive if the `#include` directive for `Arduino_ConnectionHandler.h` is left in place in the `arduino_secrets.h` files even after it is also added to `thingProperties.h`.

The reason is that this makes it easier for the user to understand the origin of the `BOARD_HAS_*` macros referenced in the file.

**Review by per1234 — CHANGES_REQUESTED** [review]

File: examples/ArduinoIoTCloud-Advanced/arduino_secrets.h (hunk 1 above)
Comment (pennam) [reply examples/ArduinoIoTCloud-Advanced/arduino_secrets.h:2]: should be fixed now! Thanks @per1234

**Review by per1234 — APPROVED** [review]
Thanks Mattia!
